In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel('flight_price.xlsx')
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

## 1.Incomplete

In [3]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [4]:
len(df)

10683

In [5]:
df.dropna(inplace = True)

In [6]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

## 2. Incorrect

In [7]:
df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

In [8]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

#### From description we can see that Date_of_Journey, Dep_Time, Arrival_time is a object data type,
     Therefore, we have to convert this datatype into timestamp so as to use this column properly for prediction,bcz our 
     model will not be able to understand Theses string values,it just understand Time-stamp
    For this we require pandas to_datetime to convert object data type to datetime dtype.


    dt.day method will extract only day of that date
    dt.month method will extract only month of that date
    
    journey_day
    journey_month
    
    dep_time_hour
    dep_time_min
    
    arrival_time_hour
    arrival_time_min

In [9]:
def convert_to_date(col):
    df[col] = pd.to_datetime(df[col])

In [63]:
columns = ['Date_of_Journey','Dep_Time', 'Arrival_Time']
for i in columns:
    convert_to_date(i)

In [56]:
def drop_col(col):
    df.drop(col,axis = 1,inplace = True)

In [59]:
df['journey_day'] = df['Date_of_Journey'].dt.day
df['journey_month']= df['Date_of_Journey'].dt.month

In [61]:
df['dep_time_hour'] = df['Dep_Time'].dt.hour
df['dep_time_min'] = df['Dep_Time'].dt.minute

In [62]:
df['arrival_time_hour'] = df['Arrival_Time'].dt.hour
df['arrival_time_min'] = df['Arrival_Time'].dt.minute

In [64]:
for i in columns:
    drop_col(i)

In [65]:
df.head()

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,Duration_hours,Duration_mins,journey_day,journey_month,dep_time_hour,dep_time_min,arrival_time_hour,arrival_time_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,0,No info,3897,2,50,24,3,22,20,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2,No info,7662,7,25,5,1,5,50,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2,No info,13882,19,0,6,9,9,25,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1,No info,6218,5,25,5,12,18,5,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1,No info,13302,4,45,3,1,16,50,21,35

## 3.Inconsistent

In [11]:
cat_col = [col for col in df.columns if df[col].dtypes == 'O']
num_col = [col for col in df.columns if df[col].dtypes != 'O']

In [12]:
for col in cat_col:
    print(f'{col} {df[col].nunique()}')
    print('\n')

Airline 12


Source 5


Destination 6


Route 128


Duration 368


Total_Stops 5


Additional_Info 10

In [13]:
for col in cat_col:
    print(f'{col} {df[col].unique()}')
    print('\n')

Airline ['IndiGo' 'Air India' 'Jet Airways' 'SpiceJet' 'Multiple carriers' 'GoAir'
 'Vistara' 'Air Asia' 'Vistara Premium economy' 'Jet Airways Business'
 'Multiple carriers Premium economy' 'Trujet']


Source ['Banglore' 'Kolkata' 'Delhi' 'Chennai' 'Mumbai']


Destination ['New Delhi' 'Banglore' 'Cochin' 'Kolkata' 'Delhi' 'Hyderabad']


Route ['BLR → DEL' 'CCU → IXR → BBI → BLR' 'DEL → LKO → BOM → COK'
 'CCU → NAG → BLR' 'BLR → NAG → DEL' 'CCU → BLR' 'BLR → BOM → DEL'
 'DEL → BOM → COK' 'DEL → BLR → COK' 'MAA → CCU' 'CCU → BOM → BLR'
 'DEL → AMD → BOM → COK' 'DEL → PNQ → COK' 'DEL → CCU → BOM → COK'
 'BLR → COK → DEL' 'DEL → IDR → BOM → COK' 'DEL → LKO → COK'
 'CCU → GAU → DEL → BLR' 'DEL → NAG → BOM → COK' 'CCU → MAA → BLR'
 'DEL → HYD → COK' 'CCU → HYD → BLR' 'DEL → COK' 'CCU → DEL → BLR'
 'BLR → BOM → AMD → DEL' 'BOM → DEL → HYD' 'DEL → MAA → COK' 'BOM → HYD'
 'DEL → BHO → BOM → COK' 'DEL → JAI → BOM → COK' 'DEL → ATQ → BOM → COK'
 'DEL → JDH → BOM → COK' 'CCU → BBI → BOM → BLR' 'BLR → MAA → DEL'
 'DEL → GOI → BOM → COK' 'DEL → BDQ → BOM → COK' 'CCU → JAI → BOM → BLR'
 'CCU → BBI → BLR' 'BLR → HYD → DEL' 'DEL → TRV → COK'
 'CCU → IXR → DEL → BLR' 'DEL → IXU → BOM → COK' 'CCU → IXB → BLR'
 'BLR → BOM → JDH → DEL' 'DEL → UDR → BOM → COK' 'DEL → HYD → MAA → COK'
 'CCU → BOM → COK → BLR' 'BLR → CCU → DEL' 'CCU → BOM → GOI → BLR'
 'DEL → RPR → NAG → BOM → COK' 'DEL → HYD → BOM → COK'
 'CCU → DEL → AMD → BLR' 'CCU → PNQ → BLR' 'BLR → CCU → GAU → DEL'
 'CCU → DEL → COK → BLR' 'BLR → PNQ → DEL' 'BOM → JDH → DEL → HYD'
 'BLR → BOM → BHO → DEL' 'DEL → AMD → COK' 'BLR → LKO → DEL'
 'CCU → GAU → BLR' 'BOM → GOI → HYD' 'CCU → BOM → AMD → BLR'
 'CCU → BBI → IXR → DEL → BLR' 'DEL → DED → BOM → COK'
 'DEL → MAA → BOM → COK' 'BLR → AMD → DEL' 'BLR → VGA → DEL'
 'CCU → JAI → DEL → BLR' 'CCU → AMD → BLR' 'CCU → VNS → DEL → BLR'
 'BLR → BOM → IDR → DEL' 'BLR → BBI → DEL' 'BLR → GOI → DEL'
 'BOM → AMD → ISK → HYD' 'BOM → DED → DEL → HYD' 'DEL → IXC → BOM → COK'
 'CCU → PAT → BLR' 'BLR → CCU → BBI → DEL' 'CCU → BBI → HYD → BLR'
 'BLR → BOM → NAG → DEL' 'BLR → CCU → BBI → HYD → DEL' 'BLR → GAU → DEL'
 'BOM → BHO → DEL → HYD' 'BOM → JLR → HYD' 'BLR → HYD → VGA → DEL'
 'CCU → KNU → BLR' 'CCU → BOM → PNQ → BLR' 'DEL → BBI → COK'
 'BLR → VGA → HYD → DEL' 'BOM → JDH → JAI → DEL → HYD'
 'DEL → GWL → IDR → BOM → COK' 'CCU → RPR → HYD → BLR' 'CCU → VTZ → BLR'
 'CCU → DEL → VGA → BLR' 'BLR → BOM → IDR → GWL → DEL'
 'CCU → DEL → COK → TRV → BLR' 'BOM → COK → MAA → HYD' 'BOM → NDC → HYD'
 'BLR → BDQ → DEL' 'CCU → BOM → TRV → BLR' 'CCU → BOM → HBX → BLR'
 'BOM → BDQ → DEL → HYD' 'BOM → CCU → HYD' 'BLR → TRV → COK → DEL'
 'BLR → IDR → DEL' 'CCU → IXZ → MAA → BLR' 'CCU → GAU → IMF → DEL → BLR'
 'BOM → GOI → PNQ → HYD' 'BOM → BLR → CCU → BBI → HYD' 'BOM → MAA → HYD'
 'BLR → BOM → UDR → DEL' 'BOM → UDR → DEL → HYD' 'BLR → VGA → VTZ → DEL'
 'BLR → HBX → BOM → BHO → DEL' 'CCU → IXA → BLR' 'BOM → RPR → VTZ → HYD'
 'BLR → HBX → BOM → AMD → DEL' 'BOM → IDR → DEL → HYD' 'BOM → BLR → HYD'
 'BLR → STV → DEL' 'CCU → IXB → DEL → BLR' 'BOM → JAI → DEL → HYD'
 'BOM → VNS → DEL → HYD' 'BLR → HBX → BOM → NAG → DEL'
 'BLR → BOM → IXC → DEL' 'BLR → CCU → BBI → HYD → VGA → DEL'
 'BOM → BBI → HYD']


Duration ['2h 50m' '7h 25m' '19h' '5h 25m' '4h 45m' '2h 25m' '15h 30m' '21h 5m'
 '25h 30m' '7h 50m' '13h 15m' '2h 35m' '2h 15m' '12h 10m' '26h 35m'
 '4h 30m' '22h 35m' '23h' '20h 35m' '5h 10m' '15h 20m' '2h 55m' '13h 20m'
 '15h 10m' '5h 45m' '5h 55m' '13h 25m' '22h' '5h 30m' '10h 25m' '5h 15m'
 '2h 30m' '6h 15m' '11h 55m' '11h 5m' '8h 30m' '22h 5m' '2h 45m' '12h'
 '16h 5m' '19h 55m' '3h 15m' '25h 20m' '3h' '16h 15m' '15h 5m' '6h 30m'
 '25h 5m' '12h 25m' '27h 20m' '10h 15m' '10h 30m' '1h 30m' '1h 25m'
 '26h 30m' '7h 20m' '13h 30m' '5h' '19h 5m' '14h 50m' '2h 40m' '22h 10m'
 '9h 35m' '10h' '21h 20m' '18h 45m' '12h 20m' '18h' '9h 15m' '17h 30m'
 '16h 35m' '12h 15m' '7h 30m' '24h' '8h 55m' '7h 10m' '14h 30m' '30h 20m'
 '15h' '12h 45m' '10h 10m' '15h 25m' '14h 5m' '20h 15m' '23h 10m'
 '18h 10m' '16h' '2h 20m' '8h' '16h 55m' '3h 10m' '14h' '23h 50m'
 '21h 40m' '21h 15m' '10h 50m' '8h 15m' '8h 35m' '11h 50m' '27h 35m'
 '8h 25m' '20h 55m' '4h 50m' '8h 10m' '24h 25m' '23h 35m' '25h 45m'
 '26h 10m' '28h 50m' '25h 15m' '9h 20m' '9h 10m' '3h 5m' '11h 30m'
 '9h 30m' '17h 35m' '5h 5m' '25h 50m' '20h' '13h' '18h 25m' '24h 10m'
 '4h 55m' '25h 35m' '6h 20m' '18h 40m' '19h 25m' '29h 20m' '9h 5m'
 '10h 45m' '11h 40m' '22h 55m' '37h 25m' '25h 40m' '13h 55m' '8h 40m'
 '23h 30m' '12h 35m' '24h 15m' '1h 20m' '11h' '11h 15m' '14h 35m'
 '12h 55m' '9h' '7h 40m' '11h 45m' '24h 55m' '17h 5m' '29h 55m' '22h 15m'
 '14h 40m' '7h 15m' '20h 10m' '20h 45m' '27h' '24h 30m' '20h 25m' '5h 35m'
 '14h 45m' '5h 40m' '4h 5m' '15h 55m' '7h 45m' '28h 20m' '4h 20m' '3h 40m'
 '8h 50m' '23h 45m' '24h 45m' '21h 35m' '8h 5m' '6h 25m' '15h 50m'
 '26h 25m' '24h 50m' '26h' '23h 5m' '7h 55m' '26h 20m' '23h 15m' '5h 20m'
 '4h' '9h 45m' '8h 20m' '17h 25m' '7h 5m' '34h 5m' '6h 5m' '5h 50m' '7h'
 '4h 25m' '13h 45m' '19h 15m' '22h 30m' '16h 25m' '13h 50m' '27h 5m'
 '28h 10m' '4h 40m' '15h 40m' '4h 35m' '18h 30m' '38h 15m' '6h 35m'
 '12h 30m' '11h 20m' '7h 35m' '29h 35m' '26h 55m' '23h 40m' '12h 50m'
 '9h 50m' '21h 55m' '10h 55m' '21h 10m' '20h 40m' '30h' '13h 10m' '8h 45m'
 '6h 10m' '17h 45m' '21h 45m' '3h 55m' '17h 20m' '30h 30m' '21h 25m'
 '12h 40m' '24h 35m' '19h 10m' '22h 40m' '14h 55m' '21h' '6h 45m'
 '28h 40m' '9h 40m' '16h 40m' '16h 20m' '16h 45m' '1h 15m' '6h 55m'
 '11h 25m' '14h 20m' '12h 5m' '24h 5m' '28h 15m' '17h 50m' '20h 20m'
 '28h 5m' '10h 20m' '14h 15m' '35h 15m' '35h 35m' '26h 40m' '28h'
 '14h 25m' '13h 5m' '37h 20m' '36h 10m' '25h 55m' '35h 5m' '19h 45m'
 '27h 55m' '47h' '10h 35m' '1h 35m' '16h 10m' '38h 20m' '6h' '16h 50m'
 '14h 10m' '23h 20m' '17h 40m' '11h 35m' '18h 20m' '6h 40m' '30h 55m'
 '24h 40m' '29h 50m' '28h 25m' '17h 15m' '22h 45m' '25h 25m' '21h 50m'
 '33h 15m' '30h 15m' '3h 35m' '27h 40m' '30h 25m' '18h 50m' '27h 45m'
 '15h 15m' '10h 40m' '26h 15m' '36h 25m' '26h 50m' '15h 45m' '19h 40m'
 '22h 25m' '19h 35m' '25h' '26h 45m' '38h' '4h 15m' '25h 10m' '18h 15m'
 '6h 50m' '23h 55m' '17h 55m' '23h 25m' '17h 10m' '24h 20m' '28h 30m'
 '27h 10m' '19h 20m' '15h 35m' '9h 25m' '21h 30m' '34h 25m' '18h 35m'
 '29h 40m' '26h 5m' '29h 5m' '27h 25m' '16h 30m' '11h 10m' '28h 55m'
 '29h 10m' '34h' '30h 40m' '30h 45m' '32h 55m' '10h 5m' '35h 20m' '32h 5m'
 '31h 40m' '19h 50m' '33h 45m' '30h 10m' '13h 40m' '19h 30m' '31h 30m'
 '34h 30m' '27h 50m' '38h 35m' '42h 5m' '4h 10m' '39h 5m' '3h 50m' '5m'
 '32h 30m' '31h 55m' '33h 20m' '27h 30m' '18h 55m' '9h 55m' '41h 20m'
 '20h 5m' '31h 50m' '42h 45m' '3h 25m' '37h 10m' '29h 30m' '32h 20m'
 '20h 50m' '40h 20m' '13h 35m' '47h 40m']


Total_Stops ['non-stop' '2 stops' '1 stop' '3 stops' '4 stops']


Additional_Info ['No info' 'In-flight meal not included' 'No check-in baggage included'
 '1 Short layover' 'No Info' '1 Long layover' 'Change airports'
 'Business class' 'Red-eye flight' '2 Long layover']

**we will split duration into hour and minute column**

**we will replace Total_Stops values as 
'non-stop':0, '2 stops':2 ,'1 stop':1, '3 stops':3 ,'4 stops':4
and then will convert into num**

*Duration*

In [14]:
df['Duration'].str.split()

0        [2h, 50m]
1        [7h, 25m]
2            [19h]
3        [5h, 25m]
4        [4h, 45m]
           ...
10678    [2h, 30m]
10679    [2h, 35m]
10680         [3h]
10681    [2h, 40m]
10682    [8h, 20m]
Name: Duration, Length: 10682, dtype: object

*here is a problem if we directly split this then if a row has only hour then it will goes to the minute column and if a row has only minute then it will come to the ist column that is hour column*

*so we will apply a approach that is if a row has only hr then add 0m and if a row has only min then add 0hr so the columns will be balanced*

In [15]:
duration = list(df['Duration'])

In [16]:
duration[1].split()

['7h', '25m']

In [17]:
len(duration[1].split())

2

In [18]:
duration[2]

'19h'

In [19]:
len(duration[2].split())

1

from above obs. it is clear if the row has hr and m then the length will be two other wise 1

don't forget to add the space of '0m ' and ' 0h'

In [20]:
for i in range(len(duration)):
    if len(duration[i].split()) == 2:
        pass
    else:
        if 'h' in duration[i]:
            duration[i] = duration[i] + ' 0m'
        else:
            duration[i] = '0h ' + duration[i]

In [21]:
duration

['2h 50m',
 '7h 25m',
 '19h 0m',
 '5h 25m',
 '4h 45m',
 '2h 25m',
 '15h 30m',
 '21h 5m',
 '25h 30m',
 '7h 50m',
 '13h 15m',
 '2h 35m',
 '2h 15m',
 '12h 10m',
 '2h 35m',
 '26h 35m',
 '4h 30m',
 '22h 35m',
 '23h 0m',
 '20h 35m',
 '5h 10m',
 '15h 20m',
 '2h 50m',
 '2h 55m',
 '13h 20m',
 '15h 10m',
 '5h 45m',
 '5h 55m',
 '2h 50m',
 '2h 15m',
 '2h 15m',
 '13h 25m',
 '2h 50m',
 '22h 0m',
 '5h 30m',
 '10h 25m',
 '5h 15m',
 '2h 30m',
 '6h 15m',
 '11h 55m',
 '11h 5m',
 '8h 30m',
 '22h 5m',
 '2h 45m',
 '12h 0m',
 '2h 50m',
 '2h 50m',
 '2h 15m',
 '16h 5m',
 '19h 55m',
 '3h 15m',
 '25h 20m',
 '2h 50m',
 '3h 0m',
 '2h 50m',
 '16h 15m',
 '15h 5m',
 '2h 15m',
 '6h 30m',
 '25h 5m',
 '12h 25m',
 '27h 20m',
 '10h 15m',
 '10h 30m',
 '2h 15m',
 '10h 25m',
 '2h 50m',
 '1h 30m',
 '13h 20m',
 '2h 15m',
 '1h 25m',
 '26h 30m',
 '7h 20m',
 '13h 30m',
 '5h 0m',
 '2h 45m',
 '2h 50m',
 '1h 30m',
 '19h 5m',
 '2h 15m',
 '14h 50m',
 '2h 40m',
 '22h 10m',
 '9h 35m',
 '10h 0m',
 '21h 20m',
 '5h 25m',
 '18h 45m',
 '12h 20m',
 '18h 0m',
 '9h 15m',
 '11h 5m',
 '17h 30m',
 '13h 20m',
 '2h 35m',
 '2h 25m',
 '2h 40m',
 '3h 0m',
 '1h 25m',
 '16h 35m',
 '12h 20m',
 '12h 15m',
 '7h 30m',
 '24h 0m',
 '2h 45m',
 '8h 55m',
 '7h 10m',
 '14h 30m',
 '30h 20m',
 '19h 55m',
 '15h 0m',
 '2h 55m',
 '12h 45m',
 '10h 10m',
 '5h 55m',
 '15h 25m',
 '16h 5m',
 '10h 10m',
 '2h 40m',
 '11h 55m',
 '2h 40m',
 '1h 25m',
 '14h 5m',
 '20h 15m',
 '2h 25m',
 '23h 10m',
 '18h 10m',
 '16h 0m',
 '2h 50m',
 '2h 20m',
 '8h 0m',
 '16h 55m',
 '3h 10m',
 '2h 45m',
 '14h 0m',
 '23h 50m',
 '21h 40m',
 '21h 15m',
 '2h 45m',
 '10h 50m',
 '8h 0m',
 '8h 15m',
 '5h 25m',
 '8h 35m',
 '11h 50m',
 '27h 35m',
 '8h 25m',
 '20h 55m',
 '4h 50m',
 '8h 10m',
 '2h 20m',
 '24h 25m',
 '2h 50m',
 '12h 20m',
 '12h 15m',
 '23h 35m',
 '16h 35m',
 '2h 50m',
 '25h 45m',
 '26h 10m',
 '28h 50m',
 '2h 45m',
 '25h 15m',
 '9h 20m',
 '4h 30m',
 '15h 25m',
 '1h 30m',
 '2h 40m',
 '9h 10m',
 '2h 45m',
 '22h 35m',
 '3h 5m',
 '11h 30m',
 '9h 30m',
 '12h 10m',
 '17h 35m',
 '5h 5m',
 '25h 50m',
 '20h 0m',
 '13h 0m',
 '18h 25m',
 '1h 30m',
 '9h 30m',
 '16h 0m',
 '2h 20m',
 '4h 30m',
 '5h 45m',
 '24h 10m',
 '2h 35m',
 '2h 45m',
 '4h 55m',
 '25h 35m',
 '6h 20m',
 '3h 5m',
 '18h 40m',
 '2h 15m',
 '12h 10m',
 '19h 25m',
 '2h 50m',
 '8h 25m',
 '9h 15m',
 '2h 50m',
 '3h 15m',
 '2h 50m',
 '12h 20m',
 '2h 55m',
 '9h 35m',
 '2h 35m',
 '9h 30m',
 '29h 20m',
 '2h 55m',
 '5h 15m',
 '9h 5m',
 '10h 45m',
 '4h 55m',
 '1h 30m',
 '11h 40m',
 '2h 45m',
 '2h 55m',
 '10h 0m',
 '2h 45m',
 '10h 15m',
 '1h 25m',
 '9h 15m',
 '22h 55m',
 '28h 50m',
 '37h 25m',
 '2h 50m',
 '1h 30m',
 '1h 30m',
 '25h 40m',
 '2h 35m',
 '6h 15m',
 '17h 30m',
 '5h 45m',
 '2h 35m',
 '25h 30m',
 '13h 55m',
 '2h 55m',
 '10h 15m',
 '8h 40m',
 '5h 30m',
 '12h 0m',
 '2h 15m',
 '2h 15m',
 '2h 50m',
 '9h 10m',
 '10h 25m',
 '2h 20m',
 '4h 30m',
 '3h 10m',
 '23h 30m',
 '27h 20m',
 '12h 35m',
 '24h 15m',
 '1h 20m',
 '2h 45m',
 '3h 0m',
 '11h 0m',
 '13h 30m',
 '2h 50m',
 '2h 55m',
 '2h 45m',
 '11h 15m',
 '14h 35m',
 '13h 55m',
 '14h 5m',
 '15h 5m',
 '2h 15m',
 '15h 0m',
 '12h 55m',
 '9h 0m',
 '12h 15m',
 '7h 40m',
 '27h 20m',
 '1h 25m',
 '1h 20m',
 '5h 30m',
 '11h 45m',
 '3h 15m',
 '24h 55m',
 '27h 20m',
 '2h 55m',
 '17h 5m',
 '2h 40m',
 '8h 0m',
 '3h 0m',
 '27h 35m',
 '7h 30m',
 '22h 55m',
 '8h 35m',
 '29h 55m',
 '22h 15m',
 '1h 20m',
 '2h 40m',
 '3h 0m',
 '12h 10m',
 '2h 35m',
 '11h 45m',
 '2h 35m',
 '1h 30m',
 '2h 40m',
 '2h 35m',
 '22h 55m',
 '14h 40m',
 '15h 25m',
 '7h 15m',
 '20h 10m',
 '20h 45m',
 '2h 30m',
 '23h 50m',
 '27h 0m',
 '5h 30m',
 '11h 50m',
 '2h 15m',
 '24h 30m',
 '2h 20m',
 '6h 30m',
 '20h 25m',
 '2h 35m',
 '2h 55m',
 '5h 35m',
 '2h 30m',
 '14h 45m',
 '12h 20m',
 '25h 30m',
 '5h 35m',
 '11h 45m',
 '2h 55m',
 '5h 40m',
 '4h 5m',
 '8h 0m',
 '2h 45m',
 '2h 40m',
 '2h 55m',
 '15h 55m',
 '23h 10m',
 '7h 20m',
 '2h 50m',
 '7h 30m',
 '3h 0m',
 '7h 45m',
 '25h 20m',
 '10h 25m',
 '30h 20m',
 '2h 35m',
 '9h 0m',
 '15h 10m',
 '28h 20m',
 '3h 0m',
 '2h 45m',
 '4h 55m',
 '2h 40m',
 '22h 10m',
 '10h 10m',
 '2h 50m',
 '4h 20m',
 '11h 0m',
 '3h 0m',
 '22h 35m',
 '3h 5m',
 '2h 40m',
 '2h 50m',
 '21h 5m',
 '11h 50m',
 '25h 35m',
 '15h 25m',
 '2h 25m',
 '3h 40m',
 '2h 55m',
 '3h 10m',
 '11h 50m',
 '2h 50m',
 '2h 50m',
 '1h 30m',
 '11h 30m',
 '8h 50m',
 '20h 15m',
 '20h 10m',
 '16h 5m',
 '12h 35m',
 '17h 5m',
 '3h 0m',
 '15h 30m',
 '11h 30m',
 '2h 20m',
 '23h 45m',
 '1h 30m',
 '2h 35m',
 '24h 45m',
 '21h 35m',
 '5h 30m',
 '12h 15m',
 '8h 5m',
 '5h 0m',
 '2h 50m',
 '6h 25m',
 '2h 20m',
 '2h 45m',
 '12h 45m',
 '15h 50m',
 '27h 0m',
 '26h 25m',
 '2h 55m',
 '24h 50m',
 '8h 40m',
 '25h 45m',
 '2h 50m',
 '6h 15m',
 '10h 30m',
 '26h 0m',
 '17h 5m',
 '21h 20m',
 '5h 35m',
 '2h 50m',
 '25h 50m',
 '12h 10m',
 '17h 5m',
 '8h 30m',
 '23h 5m',
 '9h 20m',
 '7h 55m',
 '1h 30m',
 '2h 50m',
 '2h 15m',
 '10h 0m',
 '2h 35m',
 '7h 45m',
 '2h 55m',
 '26h 20m',
 '2h 40m',
 '11h 0m',
 '19h 25m',
 '2h 55m',
 '2h 45m',
 '23h 15m',
 '9h 0m',
 '3h 10m',
 '6h 25m',
 '8h 40m',
 '2h 50m',
 '12h 20m',
 '5h 20m',
 '4h 0m',
 '9h 45m',
 '2h 55m',
 '26h 20m',
 '2h 15m',
 '9h 45m',
 '24h 55m',
 '11h 55m',
 '8h 20m',
 '17h 25m',
 '2h 50m',
 '7h 5m',
 '21h 15m',
 '5h 0m',
 '2h 25m',
 '5h 15m',
 '15h 10m',
 '11h 45m',
 '3h 0m',
 '4h 55m',
 '2h 45m',
 '2h 30m',
 '9h 45m',
 '2h 40m',
 '6h 30m',
 '5h 30m',
 '2h 40m',
 '34h 5m',
 '15h 25m',
 '9h 30m',
 '6h 5m',
 '2h 40m',
 '5h 50m',
 '2h 45m',
 '27h 20m',
 '3h 0m',
 '5h 15m',
 '16h 0m',
 '7h 0m',
 '8h 40m',
 '9h 0m',
 '2h 20m',
 '2h 20m',
 '6h 20m',
 '4h 25m',
 '2h 20m',
 '11h 5m',
 '16h 55m',
 '13h 45m',
 '25h 45m',
 '13h 55m',
 '5h 15m',
 '19h 15m',
 '7h 30m',
 '9h 0m',
 '24h 0m',
 '18h 10m',
 '2h 55m',
 '1h 30m',
 '21h 20m',
 '6h 15m',
 '14h 30m',
 '1h 20m',
 '12h 55m',
 '2h 25m',
 '22h 30m',
 '22h 55m',
 '5h 25m',
 '1h 25m',
 '7h 15m',
 '12h 20m',
 '20h 10m',
 '21h 15m',
 '2h 15m',
 '10h 30m',
 '14h 5m',
 '2h 50m',
 '16h 25m',
 '5h 15m',
 '13h 50m',
 '2h 15m',
 '7h 15m',
 '27h 5m',
 '27h 35m',
 '5h 0m',
 '2h 50m',
 '2h 50m',
 '15h 20m',
 '5h 20m',
 '10h 10m',
 '27h 35m',
 '9h 35m',
 '28h 10m',
 '14h 0m',
 '2h 35m',
 '2h 55m',
 '2h 35m',
 '4h 40m',
 '2h 30m',
 '11h 15m',
 '7h 55m',
 '8h 50m',
 '1h 25m',
 '15h 40m',
 '2h 35m',
 '2h 55m',
 '13h 25m',
 '4h 35m',
 '18h 30m',
 '2h 15m',
 '38h 15m',
 '3h 5m',
 '25h 50m',
 '3h 10m',
 '2h 50m',
 '11h 30m',
 '6h 35m',
 '27h 35m',
 '2h 35m',
 '7h 30m',
 '3h 15m',
 '9h 35m',
 '12h 30m',
 '11h 20m',
 '3h 0m',
 '2h 35m',
 '1h 30m',
 '26h 10m',
 '4h 55m',
 '2h 45m',
 '8h 40m',
 '7h 5m',
 '2h 45m',
 '24h 50m',
 '2h 20m',
 '11h 0m',
 '9h 0m',
 '2h 55m',
 '3h 5m',
 '2h 35m',
 '13h 0m',
 '1h 25m',
 '7h 35m',
 '2h 40m',
 '12h 55m',
 '29h 20m',
 '5h 0m',
 '8h 40m',
 '3h 0m',
 '3h 0m',
 '2h 45m',
 '12h 10m',
 '2h 20m',
 '7h 55m',
 '29h 35m',
 '26h 55m',
 '12h 45m',
 '7h 35m',
 '2h 30m',
 '11h 45m',
 '23h 40m',
 '13h 50m',
 '12h 50m',
 '9h 50m',
 '2h 30m',
 '21h 55m',
 '26h 10m',
 '2h 55m',
 '20h 15m',
 '20h 10m',
 '10h 55m',
 '2h 30m',
 '21h 10m',
 '2h 35m',
 '20h 40m',
 '2h 50m',
 '6h 30m',
 '30h 0m',
 '13h 10m',
 '2h 55m',
 '18h 0m',
 '8h 0m',
 '8h 45m',
 '12h 30m',
 '13h 20m',
 '6h 10m',
 '7h 30m',
 '19h 15m',
 '2h 35m',
 '12h 0m',
 '3h 0m',
 '2h 50m',
 '1h 25m',
 '23h 5m',
 '2h 50m',
 '22h 5m',
 '2h 15m',
 '5h 45m',
 '2h 50m',
 '9h 30m',
 '8h 55m',
 '17h 45m',
 '2h 50m',
 '21h 45m',
 '12h 35m',
 '1h 30m',
 '2h 15m',
 '3h 55m',
 '2h 45m',
 '7h 30m',
 '17h 20m',
 '1h 30m',
 '1h 30m',
 '30h 30m',
 '5h 0m',
 '11h 15m',
 '2h 50m',
 '19h 5m',
 '6h 35m',
 '7h 30m',
 '2h 15m',
 '2h 45m',
 '12h 45m',
 '2h 50m',
 '26h 35m',
 '12h 55m',
 '1h 30m',
 '8h 40m',
 '14h 0m',
 '23h 30m',
 '29h 55m',
 '22h 10m',
 '4h 50m',
 '2h 45m',
 '13h 30m',
 '13h 20m',
 '2h 20m',
 '11h 55m',
 '5h 10m',
 '11h 45m',
 '13h 50m',
 '3h 0m',
 '6h 10m',
 '2h 20m',
 '10h 45m',
 '2h 15m',
 '2h 55m',
 '1h 30m',
 '7h 35m',
 '26h 35m',
 '4h 45m',
 '21h 25m',
 '8h 35m',
 '8h 30m',
 '2h 15m',
 '12h 40m',
 '8h 25m',
 '25h 40m',
 '2h 45m',
 '29h 20m',
 '2h 40m',
 '2h 50m',
 '2h 20m',
 '7h 15m',
 '20h 15m',
 '11h 45m',
 '2h 35m',
 '13h 30m',
 '1h 30m',
 '24h 35m',
 '20h 35m',
 '2h 50m',
 '4h 35m',
 '2h 20m',
 '11h 45m',
 '1h 30m',
 '12h 50m',
 '24h 30m',
 '11h 30m',
 '4h 0m',
 '11h 0m',
 '5h 25m',
 '2h 35m',
 '5h 10m',
 '10h 10m',
 '26h 55m',
 '7h 15m',
 '8h 10m',
 '2h 55m',
 '5h 15m',
 '2h 20m',
 '1h 25m',
 '4h 50m',
 '2h 20m',
 '2h 20m',
 '13h 15m',
 '19h 10m',
 '22h 40m',
 '14h 50m',
 '15h 10m',
 '7h 5m',
 '1h 25m',
 '2h 55m',
 '8h 0m',
 '2h 45m',
 '14h 55m',
 '1h 30m',
 '16h 15m',
 '2h 50m',
 '5h 0m',
 '22h 15m',
 '5h 30m',
 '8h 35m',
 '15h 25m',
 '21h 0m',
 '13h 30m',
 '2h 50m',
 '6h 45m',
 '1h 30m',
 '8h 40m',
 '1h 30m',
 '2h 50m',
 '2h 35m',
 '16h 5m',
 '23h 50m',
 '27h 5m',
 '16h 15m',
 '15h 25m',
 '2h 50m',
 '8h 35m',
 '13h 50m',
 '2h 40m',
 '2h 25m',
 '3h 10m',
 '2h 55m',
 '28h 40m',
 '2h 50m',
 '2h 35m',
 '9h 40m',
 '16h 40m',
 '6h 20m',
 '27h 0m',
 '14h 35m',
 '12h 10m',
 '7h 35m',
 '2h 20m',
 '19h 10m',
 '20h 0m',
 '3h 0m',
 '5h 10m',
 '2h 40m',
 '29h 35m',
 '4h 55m',
 '3h 0m',
 '12h 30m',
 '12h 35m',
 '26h 20m',
 '13h 15m',
 '2h 50m',
 '12h 45m',
 '16h 20m',
 '2h 40m',
 '8h 15m',
 '12h 0m',
 '2h 50m',
 '11h 0m',
 '2h 20m',
 '13h 50m',
 '8h 10m',
 '12h 10m',
 '2h 40m',
 '2h 45m',
 '2h 50m',
 '24h 0m',
 '3h 0m',
 '12h 35m',
 '25h 50m',
 '2h 55m',
 '17h 5m',
 '29h 20m',
 '8h 55m',
 '3h 5m',
 '9h 0m',
 '10h 25m',
 '16h 45m',
 '2h 45m',
 '26h 20m',
 '13h 15m',
 '10h 30m',
 '7h 35m',
 '11h 0m',
 '2h 50m',
 '25h 45m',
 '6h 25m',
 '1h 25m',
 '20h 10m',
 '11h 55m',
 '2h 50m',
 '5h 0m',
 '27h 0m',
 '2h 50m',
 '1h 15m',
 '10h 15m',
 '24h 50m',
 '2h 50m',
 '20h 0m',
 '5h 30m',
 '2h 45m',
 '6h 55m',
 '2h 45m',
 '5h 15m',
 '6h 15m',
 '2h 50m',
 '19h 25m',
 '2h 55m',
 '11h 25m',
 '14h 5m',
 '2h 45m',
 '3h 15m',
 '14h 20m',
 '12h 30m',
 '5h 20m',
 '26h 20m',
 '3h 5m',
 '1h 30m',
 '7h 5m',
 '6h 10m',
 '8h 0m',
 '12h 5m',
 '12h 55m',
 '9h 35m',
 '15h 10m',
 '11h 40m',
 '2h 55m',
 '4h 30m',
 '2h 40m',
 '2h 30m',
 '24h 10m',
 '28h 20m',
 '1h 25m',
 '10h 10m',
 '11h 30m',
 '2h 50m',
 '13h 45m',
 '6h 25m',
 '12h 55m',
 '4h 25m',
 '13h 30m',
 '24h 5m',
 '16h 5m',
 '8h 20m',
 '3h 40m',
 '9h 30m',
 '28h 15m',
 '13h 20m',
 '17h 50m',
 '20h 20m',
 '28h 5m',
 '15h 25m',
 '12h 5m',
 '10h 20m',
 '12h 25m',
 '7h 35m',
 '2h 50m',
 '4h 35m',
 '11h 15m',
 '2h 35m',
 '26h 0m',
 '2h 25m',
 '2h 35m',
 '14h 15m',
 '2h 35m',
 '22h 5m',
 '6h 35m',
 '8h 30m',
 '18h 45m',
 '35h 15m',
 '2h 15m',
 '2h 30m',
 '2h 20m',
 '2h 30m',
 '7h 35m',
 '35h 35m',
 '26h 30m',
 '11h 30m',
 '26h 40m',
 '3h 0m',
 '1h 30m',
 '2h 55m',
 '14h 15m',
 '16h 55m',
 '12h 20m',
 '29h 35m',
 '20h 20m',
 '8h 25m',
 '13h 50m',
 '10h 0m',
 '19h 25m',
 '28h 0m',
 '2h 50m',
 '17h 20m',
 '2h 45m',
 '2h 55m',
 '13h 25m',
 '12h 55m',
 '9h 45m',
 '21h 25m',
 '15h 40m',
 '2h 20m',
 '14h 25m',
 '2h 50m',
 '6h 35m',
 '22h 10m',
 '14h 25m',
 '2h 30m',
 '23h 35m',
 '13h 5m',
 '1h 30m',
 '5h 5m',
 '1h 20m',
 '22h 55m',
 '1h 30m',
 '2h 35m',
 '37h 20m',
 '2h 50m',
 '2h 50m',
 '36h 10m',
 '9h 15m',
 '1h 25m',
 '5h 5m',
 '2h 15m',
 '15h 10m',
 '25h 55m',
 '5h 40m',
 '7h 30m',
 '17h 45m',
 '2h 20m',
 '8h 15m',
 '3h 40m',
 '5h 55m',
 '2h 30m',
 '17h 30m',
 '13h 50m',
 '2h 15m',
 '21h 35m',
 '9h 30m',
 '8h 40m',
 '10h 25m',
 '35h 5m',
 '14h 15m',
 '3h 0m',
 '25h 50m',
 '2h 30m',
 '8h 40m',
 '10h 0m',
 '11h 30m',
 '7h 30m',
 ...]

In [22]:
df['Duration'] = duration

split into minute and hour

In [36]:
'19h 20m'.split()[0][0:-1]

'19'

In [37]:
'19h 20m'.split()[1][0:-1]

'20'

In [48]:
def hour(x):
    return x.split()[0][0:-1]

In [51]:
df['Duration_hours'] = df['Duration'].apply(hour)

In [50]:
def minute(x):
    return x.split()[1][0:-1]

In [52]:
df['Duration_mins'] = df['Duration'].apply(minute)

lets convert these into int and drop the duration column

In [53]:
for i in ['Duration_hours' , 'Duration_mins']:
    df[i] = pd.to_numeric(df[i])

In [54]:
df.dtypes

Airline                    object
Date_of_Journey    datetime64[ns]
Source                     object
Destination                object
Route                      object
Dep_Time           datetime64[ns]
Arrival_Time       datetime64[ns]
Duration                   object
Total_Stops                 int64
Additional_Info            object
Price                       int64
Duration_hours              int64
Duration_mins               int64
dtype: object

In [55]:
drop_col("Duration")

*Total_Stops*

In [27]:
df['Total_Stops'].replace(to_replace = {'non-stop':'0', '2 stops':'2' ,'1 stop':'1', '3 stops':'3' ,'4 stops':'4'},inplace = True)

In [28]:
df['Total_Stops']

0        0
1        2
2        2
3        1
4        1
        ..
10678    0
10679    0
10680    0
10681    0
10682    2
Name: Total_Stops, Length: 10682, dtype: object

In [69]:
df['Total_Stops'] = pd.to_numeric(df['Total_Stops'])

In [70]:
cat_col=[col for col in df.columns if df[col].dtype=='O']
cat_col

['Airline', 'Source', 'Destination', 'Route', 'Additional_Info']

In [68]:
cont_col=[col for col in df.columns if df[col].dtype!='O']
cont_col

['Total_Stops',
 'Price',
 'Duration_hours',
 'Duration_mins',
 'journey_day',
 'journey_month',
 'dep_time_hour',
 'dep_time_min',
 'arrival_time_hour',
 'arrival_time_min']

35 colunmn

## 4. out of range